### ISSUE TITLE
EP86

### ISSUE THREAD

**Issue by yiranguan** [Big-Joe-Channel/edit-repo#1]
# EP86

## Notices

- Video Title：如何与自己的人脉圈保持联系？/ How to stay in contact with your network
- Thumbnail Title：需要做到这两点！
- Raw video: 2020-10-29_08-48-23 [点击下载](https://drive.google.com/drive/folders/1WiFaOXt0ZP5H5vy_bFx9CLn37W7Twovj)
- Comments：bigjoe: 剪辑的同学麻烦放一些截图上去 我说到的Linkedin的功能啊 微信的功能等等 如果有特别的case需要我提供截图的和我联系 

## Todo-List
- [x] 海报制作，文案的字要醒目，且非常非常大
- [x] raw文件调色，输出调色后待剪辑素材
- [x] 添加片头
- [x] 选择片头配乐
- [x] 加工片首音乐的音量及渐入
- [x] **剪辑正片**
- [x] 插入High-Light字幕
- [x] 插入配图
- [x] 插入推荐点赞动画
- [x] 插入点赞动画去底色
- [x] 选择片尾音乐
- [x] 加工片尾音乐的音量及渐入
- [x] 插入推荐入群二维码动画
- [x] 插入志愿者介绍
- [x] 插入加入志愿者申请邮箱
- [x] 制作片尾动画
- [x] 插入片尾图片
- [x] 添加转场动画
- [x] 输出无字幕影片
- [x] 使用《讯飞听见字幕》制作字幕，导入上一步结果，获取SRT
- [x] 导入字幕SRT
- [x] 校验字幕时间及内容
- [x] 导出带字幕影片
- [x] 导出SRT字幕文件
- [x] 导出TXT字幕文件
- [x] 上传影片、SRT、TXT、海报
- [x] 向监制申请审核

**Comment by yiranguan** [comment]
## issues
