### ISSUE TITLE
EP94

### ISSUE THREAD

**Issue by yiranguan** [Big-Joe-Channel/edit-repo#3]
# EP94

## Notices

- Video Title：工作去小公司还是大公司 （在2021年）/ Work for a small company or a large one?
- Thumbnail Title：小公司总监来告诉你升职之道
- Raw video: zhiyao1[点击下载](https://drive.google.com/file/d/1Mg8s0ufQuzOyCDO-CO9r4jaWOyrjp3B_/view?usp=sharing)
- Comments：bigjoe: zhiyao有时候有点啰嗦，该切就切，该加速就加速

## Todo-List
- [x] 海报制作，文案的字要醒目，且非常非常大
- [x] raw文件调色，输出调色后待剪辑素材
- [x] 添加片头
- [x] 选择片头配乐
- [x] 加工片首音乐的音量及渐入
- [x] **剪辑正片**
- [x] 插入High-Light字幕
- [x] 插入配图
- [x] 插入推荐点赞动画
- [x] 插入点赞动画去底色
- [x] 选择片尾音乐
- [x] 加工片尾音乐的音量及渐入
- [x] 插入推荐入群二维码动画
- [x] 插入志愿者介绍
- [x] 插入加入志愿者申请邮箱
- [x] 制作片尾动画
- [x] 插入片尾图片
- [x] 添加转场动画
- [x] 输出无字幕影片
- [x] 使用《讯飞听见字幕》制作字幕，导入上一步结果，获取SRT
- [x] 导入字幕SRT
- [x] 校验字幕时间及内容
- [x] 导出带字幕影片
- [x] 导出SRT字幕文件
- [x] 导出TXT字幕文件
- [x] 上传影片、SRT、TXT、海报
- [x] 向监制申请审核
