### ISSUE TITLE
EP-beta-fellow-0

### ISSUE THREAD

**Issue by yiranguan** [Big-Joe-Channel/edit-repo#5]
# EP-beta-fellow-0

## Notices

- Video Title：创业者必须知道的四件事
- Thumbnail Title：这四件事必须知道
- Raw video: 2020-10-29_08-48-23 [点击下载](https://www.youtube.com/watch?v=qrzk5TgCjWk)
- Comments：bigjoe: 剪辑的同学麻烦放一些截图上去 我说到的Linkedin的功能啊 微信的功能等等 如果有特别的case需要我提供截图的和我联系 

## Todo-List
- [x] 海报制作，文案的字要醒目，且非常非常大
- [ ] raw文件调色，输出调色后待剪辑素材
- [x] 添加片头
- [x] 选择片头配乐
- [x] 加工片首音乐的音量及渐入
- [x] **剪辑正片**
- [x] 插入High-Light字幕
- [ ] 插入配图
- [ ] 插入推荐点赞动画
- [ ] 插入点赞动画去底色
- [x] 选择片尾音乐
- [x] 加工片尾音乐的音量及渐入
- [ ] 插入推荐入群二维码动画
- [ ] 插入志愿者介绍
- [ ] 插入加入志愿者申请邮箱
- [x] 制作片尾动画
- [ ] 插入片尾图片
- [x] 添加转场动画
- [x] 输出无字幕影片
- [x] 使用《讯飞听见字幕》制作字幕，导入上一步结果，获取SRT
- [ ] 导入字幕SRT
- [x] 校验字幕时间及内容
- [ ] 导出带字幕影片
- [ ] 导出SRT字幕文件
- [ ] 导出TXT字幕文件
- [x] 上传影片、SRT、TXT、海报
- [x] 向监制申请审核
